version: '2'
services:
  gustos-db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  gustos-ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4002 -b '0.0.0.0'"
    ports:
      - "4002:4002"
    depends_on:
      - gustos-db
