version: '2'

services:

### Applications Code Container #############################

    applications:
      image: tianon/true

### Workspace Utilities Container ###########################

    workspace:
      build:
        context: ./workspace
        args:
          - INSTALL_PG_CLIENT=true
          - PUID=1000
          - PGID=1000
          - CHROME_DRIVER_VERSION=2.32
          - NODE_VERSION=stable
          - YARN_VERSION=latest
          - TZ=UTC
        dockerfile: "Dockerfile-72"
      volumes_from:
        - applications
      extra_hosts:
        - "dockerhost:192.168.99.101"
      ports:
        - "2222:22"
      tty: true
      networks:
        - frontend
        - backend

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./php-fpm
        args:
          - INSTALL_PGSQL=true
          - INSTALL_PG_CLIENT=true
          - INSTALL_TOKENIZER=true
        dockerfile: "Dockerfile-72"
      volumes_from:
        - applications
      volumes:
        - ./php-fpm/php72.ini:/usr/local/etc/php/php.ini
      expose:
        - "9000"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:192.168.99.101"
      environment:
        - PHP_IDE_CONFIG=laradock
      networks:
        - backend

### PHP Worker Container #####################################

    php-worker:
      build:
        context: ./php-worker
        dockerfile: "Dockerfile-72"
        args:
          - INSTALL_PGSQL=true
      volumes_from:
        - applications
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:192.168.99.101"
      networks:
        - backend

### NGINX Server Container ##################################

    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=php-fpm
          - PHP_UPSTREAM_PORT=9000
      volumes_from:
        - applications
      volumes:
        - ./logs/nginx/:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

### PostgreSQL Container ####################################

    postgres:
      build: ./postgres
      volumes:
        - ~/.laradock/data/postgres:/var/lib/postgresql
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=gustos_db
        - POSTGRES_USER=default
        - POSTGRES_PASSWORD=secret
      networks:
        - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  postgres:
    driver: "local"
